# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/test1/project/project_1.cache/wt [current_project]
set_property parent.project_path D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/test1/project/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/WorkSpace/Git_Project/RISC-V_CPU/vivado/test1/project/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/src/device.svh
set_property file_type "Verilog Header" [get_files D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/src/device.svh]
read_mem D:/WorkSpace/Git_Project/RISC-V_CPU/ready-to-run/lab1/lab1-test.mem
read_verilog -library xil_defaultlib -sv {
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/include/config.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/include/common.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/include/pipes.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/execute/alu.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/hazard/controller.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/core.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/decode/dataconfirm.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/decode/decode.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/registers/decode_execute.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/decode/decoder.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/src/device.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/src/without_delay/dist_ram_wrapper.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/execute/execute.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/registers/execute_memory.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/decode/extend.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/fetch/fetch.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/registers/fetch_decode.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/hazard/forward.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/hazard/hazard.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/memory/memory.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/registers/memory_writeback.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/mycpu_top_nodelay.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/fetch/pcselect.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/regfile/regfile.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/src/without_delay/soc_top_nodelay.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vsrc/pipeline/writeback/writeback.sv
  D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/src/without_delay/basys3_top_nodelay.sv
}
read_ip -quiet D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/test1/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/WorkSpace/Git_Project/RISC-V_CPU/vivado/test1/src/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Git_Project/RISC-V_CPU/vivado/test1/src/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Git_Project/RISC-V_CPU/vivado/test1/src/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/src/Basys-3-Master.xdc
set_property used_in_implementation false [get_files D:/WorkSpace/Git_Project/RISC-V_CPU/vivado/src/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top basys3_top_nodelay -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef basys3_top_nodelay.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file basys3_top_nodelay_utilization_synth.rpt -pb basys3_top_nodelay_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
